### ISSUE TITLE
Requirements Elicitation (Anforderungserhebung)

### ISSUE THREAD

**Issue by easys1lex** [easys1lex/projectvibe#10]
@Fravid @Hannes98
Anfordeungserhebung an die zu erstellende Software nach [SOPHIST](https://github.com/easys1lex/projectvibe/blob/Additional-Feed/SOPHIST_Broschuere_MASTeR.pdf) Standart.

- [x] Funktionale Anforderungen
- [x] Nichtfunktionale Anforderungen

**Comment by Fravid** [comment]
Das System soll in der Lage sein terminisierte E-Mails automatisch an Kunden zu schicken

**Comment by Hannes98** [comment]
Das System soll in der Lage sein den zeitlichen "Kundenverlauf" grafisch durch einen Zeitstrahl dazustellen.

**Comment by Fravid** [comment]
Das System soll in der Lage sein Termine mit einem Kunden zu ertellen

**Comment by Hannes98** [comment]
Das System soll in der Lage sein aus dem Zeitstrahl definierte Ereignisse zu identifizieren.

**Comment by easys1lex** [comment]
Wär ja cool wenn man eine zeitliche Darstellung für die Visualisierung Machen könnte.
Die Gui muss dem Nutzer die Möglichkeit bieten einen Kunden anzulegen.
Die Gui muss dem Nutzer die Möglichkeit bieten einen Kunden zu löschen.
Die Gui muss dem Nutzer die Möglichkeit geben einen Kunden persistent zu speichern.
Die Gui muss dem Nutzer die Möglichkeit bieten einen persistent gespeicherten Kunden zu laden.
Die Gui muss dem Nutzer die Möglichkeit bieten den Datensatz zu wechseln.
Die Gui muss dem Nutzer die Möglichkeit bieten den Datensatz persistent zu speichern.
Die Gui muss dem Nutzer die Möglichkeit bieten einen persistenten Datensatz zu laden.
Das System sollte - den zuletzt genutzen Datensatz automatisch laden.
Die Gui sollte - dem Nutzer automatisch einen Datensatz anzeigen.
Falls noch kein Datensatz existiert sollte die Gui, dem Nutzer die Möglichkeit bieten einen neuen Datensatz anzulegen.
Die Gui muss dem Nutzer die Möglichkeit bieten einen Kunden zu bearbeiten.

Das System muss fähig sein einen Kunden anzulegen.
Das System muss fähig sein einen Kunden zu löschen.
Das System muss fähig sein einen Kunden persistent zu speichern.
Das System muss fähig sein eine persistente Kundendatei zu laden.

Das System muss fähig sein einen Datensatz persistent zu speichern.
Das System muss fähig sein einen persistenten Datensatz zu laden.
Das System muss fähig sein einen Kunden zu bearbeiten.

Das System muss fähig sein zwischen BusinessKunden und PrivatKunden zu unterscheiden.
Ereignisse
Ein Kunde muss eine Kundennummer besitzen.
Ein Kunde muss einer E-Mail Adresse zuordbar sein.
Ein Kunde muss ein Ersellungsdatum Besitzen.
Ein PrivatKunde muss einem Vor- und Nachnamen zuordbar sein.
Ein PrivatKunde sollte ein Geburtsdatum besitzen.
Ein Kunde sollte ein Geschlecht besitzen.

**Comment by Fravid** [comment]
FUNKTIONAL:

# Datensätze
- Das System muss in der Lage sein neue Datensätze anzulegen
- Das System muss in der Lage sein Datensätze zu entfernen
- Das System muss in der Lage sein Datensätze zu bearbeiten
- Das System muss in der Lage sein Datensätze persistent zu speichern
- Das System muss in der Lage sein persistente Datensätze zu laden

# Kommunikation
- Das System muss in der Lage sein Kunden nach Informationen/tags zu filtern
- Das System muss in der Lage sein Kunden direkt aus dem System E-Mails zu schicken
- Das System soll in der Lage sein terminisierte E-Mails automatisch an Kunden zu schicken
- Das System soll in der Lage sein Termine mit einem Kunden zu erstellen
- Das System soll in der Lage sein Erinnerungen zu Terminen einzublenden (z.B. 14:00 Uhr - Max Muster anrufen)
- Das System muss ein Aktivitätenprotokollposten für Kunden haben

# Aufträge und Anhänge
- Das System muss in der Lage sein Aufträge Kunden zuzuordnen
- Das System soll in der Lage sein Word Dateien an Datensätze zu hängen


NICHT FUNKTIONAL:
- Fenster soll vergrößerbar bzw. verkleinerbar sein
- Die GUI soll intuitiv sein
- Die GUI soll ein Terminkalender beinhalten

**Comment by Hannes98** [comment]
Das System soll in der Lage sein den zeitlichen individuellen "Kundenverlauf" grafisch durch einen Zeitstrahl dazustellen.

Das System soll in der Lage sein aus dem Zeitstrahl definierte Ereignisse zu identifizieren. 
Ereignisse: - erster Kontakt 
                  - erreichen bestimmter Anzahl an Wareneinkäufe / -verkäufe
                  - erreichen zeitlicher "Schranken" (ganzjährig: z.B. nach einem Jahr, nach 5 Jahren, nach 10 
                    Jahren, ...  --> Treue)
                  - ...
--> mögliches Versenden von E-Mails an den Kunden mit Informationen, Glückwünsche, Vorteile (Aktionsrabatten, weiterer Angebote, ...)

**Comment by easys1lex** [comment]
Denkt an Paketierung!!! Versionierung..

**Comment by Fravid** [comment]
![20180607_145350](https://user-images.githubusercontent.com/39947102/41102572-875deed4-6a67-11e8-8c2f-fda8533e00ad.jpg)

Erste Idee für GUI

**Comment by Hannes98** [comment]
Folgendes habe ich im Internet bei meiner Recherche gefunden, damit ich es nicht vergesse: 

Ein absolutes Muss für ein CRM-System ist die Funktionalität der Historienspeicherung. In folgenden Bereichen sollte es eine Historie bzw. einen Verlauf zum Nachvollziehen geben:

- Versendete E-Mails an den Kunden
- Rechnungen und Angebote
- Verträge, Mahnungen und Kündigungen
- Postalischer Briefverkehr
- Getätigte Käufe, Artikeldetails
- Anrufe, Beschwerden, Anfragen
- Servicezufriedenheit: Kritik und Lob

Einiges haben wir uns auch schon überlegt, Anderes könnte man sich noch überlegen mit rein zu nehmen, sofern es möglich ist.

**Comment by easys1lex** [comment]
> Historienspeicherung
Das setzen wirt doch mittels Ereignisspeicherung um, oder?

**Comment by easys1lex** [comment]
Ich denke, wir haben dieses Issue schließen können. Bearbeitungszeit: 4 Tage.

**Comment by easys1lex** [comment]
Ich denke, wir haben dieses Issue schließen können. Bearbeitungszeit: 4 Tage.
