### ISSUE TITLE
Ziele des Projektes Analysieren

### ISSUE THREAD

**Issue by easys1lex** [easys1lex/projectvibe#13]
Welche Ziele wollen wir in diesem Projekt verfolgen?

**Comment by Fravid** [comment]
Comment geht

**Comment by easys1lex** [comment]
Wir formulieren Leitlinien:

Unser Ziel ist eine sehr gute Bewertung: 1.0 - 1.3 halten wir für erstrebenswert!

Wir wollen eine Version 1.0 Herrausbringen.
Featuren von GitHub kennenlernen und nutzen.
Keine GitHub Wiki - Page erstellen.

Wir legen Wert auf Vollständigkeit.
